
import { validationResult } from "express-validator";
import ApiError from "../exceptions/ApiError.js";
import userService from "../service/userService.js";
import commentModel from "../models/commentModel.js";

// создаем класс для CommentController,где будем описывать функции для эндпоинтов
class CommentController {

    // первым параметром эти функции принимают req(запрос),а вторым параметром res(ответ),третьим параметром передаем функцию next(следующий по цепочке middleware,в данном случае это наш errorMiddleware)
    async createComment(req, res, next) {

        // оборачиваем в try catch для обработки ошибок
        try {

            const comment = req.body; // достаем(деструктуризируем) из тела запроса весь объект запроса со всеми полями,которые мы передали с фронтенда(не используем здесь деструктуризацию типа деструктурировать из req.body {comment} в квадратных скобках,так как просто берем все тело запроса,то есть весь объект тела запроса,а не отдельные поля)

            const commentCreated = await commentModel.create({ ...comment }); // создаем объект комментария в базе данных,разворачивая весь объект comment(это весь объект тела запроса),вместо ...comment будут подставлены все поля с их значениями,которые есть в объекте тела запроса

            return res.json(commentCreated); // возвращаем созданный объект комментария на фронтенд

        } catch (e) {

            next(e); // вызываем функцию next()(параметр этой функции getProducts) и туда передаем ошибку,в этот next() попадает ошибка,и если ошибка будет от нашего класса ApiError(наш класс обработки ошибок,то есть когда мы будем вызывать функцию из нашего класса ApiError для обработки определенной ошибки,то эта функция будет возвращать объект с полями message и тд,и этот объект будет попадать в эту функцию next(в наш errorMiddleware) у этой нашей функции getProducts,и будет там обрабатываться),то она будет там обработана с конкретным сообщением,которое мы описывали,если эта ошибка будет не от нашего класса ApiError(мы обрабатывали какие-то конкретные ошибки,типа UnauthorizedError,ошибки при авторизации и тд),а какая-то другая,то она будет обработана как обычная ошибка(просто выведена в логи,мы это там прописали),вызывая эту функцию next(),мы попадаем в наш middleware error-middleware(который подключили в файле index.js)

        }

    }

    async getCommentsForProduct(req, res, next) {

        // оборачиваем в try catch для обработки ошибок
        try {

            const { productNameFor } = req.query; // берем из url(строки) запроса параметр productNameFor,чтобы получить все комментарии для конкретного товара

            const comments = await commentModel.find({ productNameFor }); // получаем все объекты комментариев,у которых productNameFor равен параметру productNameFor,который мы взяли из url(строки) запроса,можно было указать и productNameFor:productNameFor,но так как названия параметра(который мы взяли из параметров запроса) и поля одинаковые,то можно указать просто productNameFor

            return res.json(comments); // возвращаем эти комментарии на фронтенд

        } catch (e) {

            next(e); // вызываем функцию next()(параметр этой функции getProducts) и туда передаем ошибку,в этот next() попадает ошибка,и если ошибка будет от нашего класса ApiError(наш класс обработки ошибок,то есть когда мы будем вызывать функцию из нашего класса ApiError для обработки определенной ошибки,то эта функция будет возвращать объект с полями message и тд,и этот объект будет попадать в эту функцию next(в наш errorMiddleware) у этой нашей функции getProducts,и будет там обрабатываться),то она будет там обработана с конкретным сообщением,которое мы описывали,если эта ошибка будет не от нашего класса ApiError(мы обрабатывали какие-то конкретные ошибки,типа UnauthorizedError,ошибки при авторизации и тд),а какая-то другая,то она будет обработана как обычная ошибка(просто выведена в логи,мы это там прописали),вызывая эту функцию next(),мы попадаем в наш middleware error-middleware(который подключили в файле index.js)

        }

    }


}

export default new CommentController(); // экспортируем уже объект на основе нашего класса CommentController